const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';

const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';

const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export { AUTH_LOGIN_SUCCESS, FETCH_USERS_SUCCESS, LOGOUT_SUCCESS };
