const ACTIVATE_LOADER = 'ACTIVATE_LOADER';
const ADD_NEW_QUESTION_SUCCESS = 'ADD_NEW_QUESTION_SUCCESS';
const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
const FETCH_QUESTIONS_SUCCESS = 'FETCH_QUESTIONS_SUCCESS';
const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
const SAVE_QUESTION_ANSWER_SUCCESS = 'SAVE_QUESTION_ANSWER_SUCCESS';
const SET_QUESTIONS_TO_DEFAULT_STATE = 'SET_QUESTIONS_TO_DEFAULT_STATE';

export {
  ACTIVATE_LOADER,
  ADD_NEW_QUESTION_SUCCESS,
  AUTH_LOGIN_SUCCESS,
  FETCH_QUESTIONS_SUCCESS,
  FETCH_USERS_SUCCESS,
  LOGOUT_SUCCESS,
  SAVE_QUESTION_ANSWER_SUCCESS,
  SET_QUESTIONS_TO_DEFAULT_STATE,
};
