const ADD_QUESTION_PAGE_URL = '/add';
const DASHBOARD_PAGE_URL = '/';
const LEADER_BOARD_PAGE_URL = '/leader-board';
const LOGIN_PAGE_URL = '/login';

export {
  ADD_QUESTION_PAGE_URL,
  DASHBOARD_PAGE_URL,
  LEADER_BOARD_PAGE_URL,
  LOGIN_PAGE_URL,
};
